version: 0.2

# The `buildspec.yml` is the instruction manual for the CodeBuild worker.
phases:
  install:
    commands:
      # This command ensures we have the AWS Serverless Application Model (SAM)
      # command-line tool available in the build environment.
      - |
        if ! command -v sam &> /dev/null
        then
            echo "SAM CLI not found. Installing..."
            pip install aws-sam-cli
        else
            echo "SAM CLI is already installed."
        fi

  build:
    commands:
      - echo "Starting the SAM package build..."
      # CRITICAL: The `sam package` command is what prepares your code for deployment.
      # It zips the contents of the `CodeUri` folder (`./src/`), uploads it to the
      # S3 bucket, and then creates a new CloudFormation template (`packaged.yaml`)
      # that references the new location of the code in S3.
      - sam package --template-file project-tracker-backend.yaml --s3-bucket $LambdaCodeBucketName --output-template-file packaged.yaml

# The `artifacts` section tells the pipeline which files to send to the next stage.
# We are now sending the `packaged.yaml` file, not the source files.
artifacts:
  files:
    - packaged.yaml
